# Generated by Django 6.0.3 on 2026-03-06 13:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
